### ISSUE TITLE
"Failed to load: Error: Unknown field_name: Permission"

### ISSUE THREAD

**Issue by lylat1an** [scottanderson/railroad.studio#191]
**Attach the save file**
Add the .sav file to a zip, and attach the .zip file to this issue.

[PV 35.zip](https://github.com/user-attachments/files/16258039/PV.35.zip)

**Describe the bug**

Since the Loading Screen & Rights and Alerts update, I have been unable to load my save into the online version of Railroad.Studio:  It gives me the error in the bug title.

**To Reproduce**

1. Go to 'Railroad.Studio'
2. Click on 'Browse'
3. Scroll down to 'latest save'
4. Select Open
5. See error

**Expected behavior**
I expected Railroad Studio to open my save.

**Screenshots**
![Screenshot 2024-07-16 181757](https://github.com/user-attachments/assets/b2fcef38-0e95-444a-bdc8-44f87738c03c)

**Desktop (please complete the following information):**

-   OS: Windows 10 Home x64
-   Browser: Firefox
-   Version: 128.0 (64-bit)

**Additional context**
Issue started when the Loading Screen & Rights and Alerts Update update hit the Beta branch, and is still occurring now that the update has been pushed to the Main branch.

**Comment by scottanderson** [comment]
This was fixed in #184

**Comment by Pyrotrainthing** [comment]
#184  is not fixed. Permissions still break save loading.
[RRStudioIssue184.zip](https://github.com/user-attachments/files/16340637/RRStudioIssue184.zip) 3 example save files as proof none work in Railroad Studio.
Screenshot:
![image](https://github.com/user-attachments/assets/8a955f4d-0d08-4484-aad2-205b003098ef)

**Comment by scottanderson** [comment]
@Pyrotrainthing it looks like your web browser may be caching an old version of Railroad Studio. You can force it to re-load the latest code  by holding ctrl when you press the refresh button.

**Comment by lylat1an** [comment]
Looks to be working again for me now, thank you.

**Comment by Pyrotrainthing** [comment]
Thank you @scottanderson your solution worked, I rescind my statement before.
